---
title: "Final Data"
author: "Mari Roberts"
date: "7/15/2020"
output: pdf_document
---

This RMD file runs a cluster analysis, cleans food data, and writes the final data csv.

# Questions Asked Once
```{r eval=FALSE, include=FALSE}
####################################################
# load file that loads data, libraries, and custom functions
####################################################

# load necessary packages
requiredPackages = c('foreign', # read dta
                     'dplyr', # data manipulation
                     'haven',
                     'gridExtra', # data manipulation
                     'readr', # read files
                     'readxl',# read files
                     'dummies', # PCA
                     'lubridate', # data manipulation
                     'data.table', # data manipulation
                     'FactoMineR', # PCA
                     'factoextra', # PCA
                     'psych', # PCA
                     'nFactors', # PCA
                     'lattice', # plots
                     'glmnet', # lasso
                     'caret', # lasso
                     'ggplot2', # plots
                     'cluster', # clustering
                     'Rtsne', # clustering
                     'scales', #custom color scale
                     'tidyverse') # missing values using map
# only downloads packages if needed
for(p in requiredPackages){
  if(!require(p,character.only = TRUE)) install.packages(p)
  library(p,character.only = TRUE)
}

# set wd
mydirectory <- "/Users/mari/AgricultureModel/Datasets"
setwd(mydirectory)

filenames <- list.files(path=mydirectory, pattern=".*dta")

# read in each dta file found in Dataset folder
filenames <- list.files(path=mydirectory, pattern=".*dta")
for (i in 1:length(filenames)){
  assign(filenames[i], read_dta(paste("", filenames[i], sep=''))
  )}


# custom functions
# remove outliers 
outliers <- function(x){
  quantiles <- quantile( x, c(.00, .95 ) )
  x[ x < quantiles[1] ] <- quantiles[1]
  x[ x > quantiles[2] ] <- quantiles[2]
  x
}

####################################################
## Health and Demographics
####################################################

##########################
# Basic Info
##########################

# find number of hh members for calculations later
hh_count <- HouseholdComposition_level_1.dta %>% select(hh_ID, member_1_ID, hh_members) 
hh_count <- hh_count %>% distinct(hh_ID, .keep_all = TRUE)

# rename variables
hh <- HouseholdComposition_members_level_2.dta %>% mutate(canStandOwn = hhm_health1,
                                                              canWalk5Km = hhm_health2,
                                                              canCarry20L = hhm_health3)
# merge with hh_count
hh <- merge(hh_count, hh, by=c("hh_ID","member_1_ID"))

# combine 0 and 77 ("no" and "don't know")
hh_all <- hh %>% mutate(canCarry20L = ifelse(canCarry20L==77 | canCarry20L==0, 0, 1),
                            canWalk5Km = ifelse(canWalk5Km==77 | canWalk5Km==0, 0, 1),
                            canStandOwn = ifelse(canStandOwn==77 | canStandOwn==0, 0, 1))

# 0 = male, 1 = female 
# select variables
hh_all <- hh_all %>% mutate(sex = ifelse(hhm_sex == 1,0,1),) %>% 
                       select(hh_ID,
                              member_1_ID,
                              member_2_ID,
                              hh_members,
                              currentposition,
                              hhm_relation,
                              sex,
                              age = hhm_age,
                              maritalStatus = marital_status,
                              literacy,
                              education,
                              attendingCollege = hhm_attending,
                              occupationType = hhm_occu_type,
                              #hhm_occupation,
                              canCarry20L,
                              canWalk5Km,
                              canStandOwn)

# change into factor variables
hh_all$sex = factor(hh_all$sex)
hh_all$maritalStatus = factor(hh_all$maritalStatus)
hh_all$literacy = factor(hh_all$literacy)
hh_all$education = factor(hh_all$education)
hh_all$attendingCollege = factor(hh_all$attendingCollege)
hh_all$occupationType = factor(hh_all$occupationType)

# does hh have children?
hh_all <- hh_all %>% mutate(isChild = ifelse(age>=18, 0, 1))
hh_children <- hh_all %>% group_by(hh_ID) %>% tally(isChild)
hh_children <- hh_children %>% mutate(numChildren = n) %>% select(hh_ID, numChildren)

# merge number of children dataset with hh_all
hh_all <- merge(hh_children, hh_all, by = "hh_ID")
# factor variables
hh_all$isChild <- factor(hh_all$isChild)

##########################
# Health by Household
##########################

# count health measures per household
hh_subset <- hh_all %>% select(hh_ID, member_1_ID, canCarry20L, canWalk5Km, canStandOwn)
          carry <- hh_subset %>% group_by(hh_ID) %>% tally(canCarry20L)
          walk <- hh_subset %>% group_by(hh_ID) %>% tally(canWalk5Km)
          stand <- hh_subset %>% group_by(hh_ID) %>% tally(canStandOwn)

# determine percentage of health measure per household
hh_health <- merge(hh_all, carry, by = "hh_ID") 
hh_health <- merge(hh_health, walk, by = "hh_ID") 
hh_health <- merge(hh_health, stand, by = "hh_ID") 

hh_health <- hh_health %>% mutate(totalCanCarry20L = n.x,
                                  totalCanWalk5Km = n.y,
                                  totalCanStandOwn = n)

hh_health <- hh_health %>% mutate(pctCanCarry20L = totalCanCarry20L/hh_members,
                                  pctCanWalk5Km = totalCanWalk5Km/hh_members,
                                  pctCanStandOwn = totalCanStandOwn/hh_members) %>% 
                           select(-n.x,-n.y,-n)

# remove percentages above 100, differences in number of members
hh_health <- hh_health %>% filter(pctCanCarry20L <= 1 &
                                  pctCanWalk5Km <= 1 &
                                  pctCanStandOwn <= 1)

# factor variables
hh_health$canCarry20L = factor(hh_health$canCarry20L)
hh_health$canWalk5Km = factor(hh_health$canWalk5Km)
hh_health$canStandOwn = factor(hh_health$canStandOwn)

####################################################
# Respondent info and health of household members
####################################################

# data about respondents
hh_respondent <- hh_health %>% filter(hhm_relation == 1)

# remove variables
hh_respondent <- hh_respondent %>% select(-member_1_ID,
                                          -member_2_ID,
                                          -currentposition,
                                          -hhm_relation,
                                          -totalCanCarry20L,
                                          -totalCanStandOwn,
                                          -totalCanWalk5Km,
                                          -isChild)
```

# Food Data
```{r}
#############################################################################################################################
#############################################################################################################################
# *Food Data:*  
# - Noncrowdsourced  
# - Recall period = week  
# - Calculated calories per food item(s) reported  
# - Calculated average calories (per hh member) per week by household  
# - Cleaned foods reported as counts (needs a second look)  
# - Standardized calories to calories per gram (needs a second look)   
#############################################################################################################################
#############################################################################################################################

# select noncrowdsourced data and recall period of a week
fooddiary_1 <- `33.FoodDiary_level_1.dta` %>% filter(crowdsource==0 & recall=="week")

# select variables
fooddiary_1 <- fooddiary_1 %>% select(hh_ID, 
                                      food_1_ID,
                                      submissiondate, 
                                      recall, # month 516 season 272 week 4944
                                      week_number, #3:50 weeks
                                      food_list, # groups of foods consumed
                                      food_count) # number of foods selected
fooddiary_2 <- `34. FoodDiary_food_level_2.dta` %>% select(hh_ID, 
                                      food_1_ID,
                                      food_2_ID,
                                      food_grp_namec, 
                                      food_type) #will require grepl
fooddiary_3 <- `35. Fooddiary_food_foodtype_level_3.dta` %>% select(hh_ID, 
                                      food_2_ID,
                                      food_3_ID,
                                      food_ID = food_type_name, 
                                      food_type_quant,
                                      food_type_unit,
                                      quant_pur, #How much consumed was purchased?
                                      quant_own, #How much consumed was own production?
                                      quant_other) #How much consumed was from other sources?

# merge levels 1 and 2
fooddiary_1_2 <- merge(fooddiary_1,fooddiary_2, by=c("hh_ID","food_1_ID"))

# merge with level 3
fooddiary_all <- merge(fooddiary_1_2,fooddiary_3, by=c("hh_ID","food_2_ID"))

# remove unwanted variables
fooddiary_all <- fooddiary_all %>% select(-food_type) # duplicate variable

# 118 food_type_name are missing
# remove missing values for now.
fooddiary_all <- fooddiary_all[complete.cases(fooddiary_all),]

########################################################################################################################
# Food Spreadsheets (Calories, List of Food Names)
########################################################################################################################
# food names
food_list <- read_csv("Datasets/food_list.csv") # names of food and ID number
food_calories <- read_csv("Datasets/food_cal.csv") # names of food and calorie information 
food_calories <- food_calories %>% mutate(food_name = food_type)  %>% 
                                   select(-food_type)
food_info <- merge(food_calories, food_list, by="food_name") # combine datasets together
# write csv - use for later
write.csv(food_info, "food_info.csv")

##############################
# Calories
##############################
# Carbohydrates provide 4 calories per gram, protein provides 4 calories per gram, and fat provides 9 calories per gram
# food_info <- food_info %>% filter(calorie_grams != 0)

# merge with food list names 
fooddiary_cleaned <- merge(food_info, fooddiary_all, by="food_ID")
# select variables
fooddiary_cleaned <- fooddiary_cleaned %>% select(hh_ID,
                                                  submissiondate,
                                                  recall,
                                                  week_number,
                                                  food_ID,
                                                  food_count,
                                                  food_name,
                                                  food_name_type,
                                                  food_type_quant,
                                                  food_type_unit,
                                                  quant_pur,
                                                  quant_own,
                                                  quant_other,
                                                  food_1_ID,
                                                  food_2_ID,
                                                  food_3_ID)

# calculate percent purchased, grown, other
fooddiary_cleaned <- fooddiary_cleaned %>% mutate(quant_pur_pct = quant_pur/food_type_quant,
                                                  quant_own_pct = quant_own/food_type_quant,
                                                  quant_other_pct = quant_other/food_type_quant)

# merge with food calories/info
fooddiary_cleaned <- merge(fooddiary_cleaned, food_info, by=c("food_ID","food_name_type","food_name"))

# reorder variables
fooddiary_cleaned <- fooddiary_cleaned %>% select(hh_ID,
                                                  submissiondate,
                                                  recall,
                                                  week_number,
                                                  food_ID,
                                                  food_count,
                                                  food_name,
                                                  food_name_type,
                                                  food_type_quant,
                                                  food_type_unit,
                                                  calories_grams,
                                                  quant_pur,
                                                  quant_own,
                                                  quant_other,
                                                  quant_pur_pct,
                                                  quant_own_pct,
                                                  quant_other_pct,
                                                  food_1_ID,
                                                  food_2_ID,
                                                  food_3_ID)

# fix dates and times
fooddiary_cleaned <- fooddiary_cleaned %>%
  mutate(datetime = as.POSIXct(strptime(submissiondate, format = "%b %d, %Y %I:%M:%S %p")),
         datetime_military = strftime(datetime, format = "%Y-%m-%d %H:%M"))
fooddiary_cleaned <- fooddiary_cleaned %>% mutate(date_new = as.Date(as.POSIXct(strptime(datetime_military, format = "%Y-%m-%d"))))

# create date for weeks
# check for different week number dates and replace with the max date
new_min <- fooddiary_cleaned %>% group_by(week_number) %>% summarise(min(date_new))
new_min <- new_min %>% mutate(week_date = `min(date_new)`) %>% select(-`min(date_new)`)

###################
# *Food Type Unit* - need to be standardized
###################
# 1	Kg          *1000
# 2	Grams
# 3	Liter       *1000
# 4	Milliliter  
# 5	Tablespoon  *15
# 6	Teaspoon    *4.2
# 7	Drops       *0.05
# 8	Count

# unit conversions
fooddiary_cleaned <- fooddiary_cleaned %>% 
  mutate(calories_total_grams = case_when((food_type_unit==1) ~ calories_grams*(food_type_quant*1000),
                                          (food_type_unit==2) ~ calories_grams*food_type_quant,
                                          (food_type_unit==3) ~ calories_grams*(food_type_quant*1000),
                                          (food_type_unit==4) ~ calories_grams*(food_type_quant), 
                                          (food_type_unit==5) ~ calories_grams*food_type_quant,
                                          (food_type_unit==6) ~ calories_grams*(food_type_quant*4.2),
                                          (food_type_unit==7) ~ calories_grams*(food_type_quant*0.05)))

# rearrange columns
fooddiary_cleaned <- fooddiary_cleaned %>% select(hh_ID,
                                                  submissiondate,
                                                  recall,
                                                  week_number,
                                                  food_ID,
                                                  food_count,
                                                  food_name,
                                                  food_name_type,
                                                  food_type_quant,
                                                  food_type_unit,
                                                  calories_grams,
                                                  calories_total_grams,
                                                  quant_pur,
                                                  quant_own,
                                                  quant_other,
                                                  quant_pur_pct,
                                                  quant_own_pct,
                                                  quant_other_pct,
                                                  #time_of_day,
                                                  food_1_ID,
                                                  food_2_ID,
                                                  food_3_ID)
# head(fooddiary_cleaned)
# 
# summary(fooddiary_cleaned$calories_total_grams)

    # Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
    #    0     1200     3000    17994     6000 12000000     2491 

#####################################  
## Fix Food Units Claimed As Counts
#####################################

# food unit type selected = 8
fooddiary_count <- fooddiary_cleaned %>% filter(food_type_unit == 8) %>% arrange(desc(food_name_type))

#########################################
# fix outliers
# If food type quant is more than 100 is meat 
# or fish then change to grams which was likely the intention
# convert to total calories reported in grams
# this needs more work
#########################################

fooddiary_count$calories_total_grams = as.numeric(
  
ifelse(fooddiary_count$food_name_type %in% c('fishlarge') & fooddiary_count$food_type_quant > 100, 
       fooddiary_count$calories_grams*fooddiary_count$food_type_quant,
         
         ifelse(fooddiary_count$food_name_type %in% c('fishsmall') & fooddiary_count$food_type_quant > 100, 
                fooddiary_count$calories_grams*fooddiary_count$food_type_quant,
                
                ifelse(fooddiary_count$food_name_type %in% c('meategg') & fooddiary_count$food_type_quant > 100, 
                       fooddiary_count$calories_grams*fooddiary_count$food_type_quant, 
                       
                       # grains (changed to kg)
                       case_when(fooddiary_count$food_name=="Parboiled rice (coarse)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Fine rice" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Atta" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Non-parboiled rice (coarse)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Semai/noodles" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Chira (flattened rice)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Muri/Khoi (puffed rice)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 # meats (mostly changed to kg)
                                 fooddiary_count$food_name=="Beef/buffalo" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Mutton" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Chicken" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Pigeon" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Fish egg" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant, # egg roe = 1g
                                 fooddiary_count$food_name=="Egg" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*50, # egg = 50g
                                 fooddiary_count$food_name=="Duck" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Stomach of beef/goat" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Dried meat" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Bids/bok/gughu" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Liver" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 # drinks/dairy (can = 340grams/12 fl oz)
                                 fooddiary_count$food_name=="Tea –prepared" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 fooddiary_count$food_name=="Coke/ Seven-up etc/Pepci/RC/Urocola etc" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 fooddiary_count$food_name=="Milk" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 fooddiary_count$food_name=="Milk in Tea" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 fooddiary_count$food_name=="Powdered Milk" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*35,# serving of powdered milk
                                 fooddiary_count$food_name=="Condensed Milk" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 fooddiary_count$food_name=="Butter" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*113, # serving of butter
                                 fooddiary_count$food_name=="Yogurt" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 fooddiary_count$food_name=="Cottage cheese or Paneer" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340, 
                                 fooddiary_count$food_name=="Buttermilk" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340, 
                                 fooddiary_count$food_name=="Solid Cheese Curds" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340, 
                                 fooddiary_count$food_name=="Ice Cream" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 fooddiary_count$food_name=="Ice cream" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*340,
                                 # fish small (avg  serving size 170)
                                 # some gura mach in 500 for quantity.....fix later???????
                                 fooddiary_count$food_name=="Gura mach" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Panch mishali" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Palshe" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Tatkeni" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Puti" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Tengra" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Karfu fish" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Bata" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Kajari" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*170,
                                 fooddiary_count$food_name=="Small prawn" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*3,
                                 fooddiary_count$food_name=="Dried small shrimp/prawn" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*3,
                                 # pulses (avg serving size and average size (nuts))
                                 fooddiary_count$food_name=="Khesari" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Dried Lentil" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Shem bitchi" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Anchor daal" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Dried Chick pea" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Mung" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Black gram" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Dried Pea" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*160,
                                 fooddiary_count$food_name=="Groundnut" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Brazilnut" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Cashew Nut" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Almond/Badam" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Hazelnut" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Chestnut" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 # fix vegetables (avg serving size per item)
                                 fooddiary_count$food_name=="Patal" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Okra" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Eggplant" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*141,
                                 fooddiary_count$food_name=="Bitter gourd" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*125,
                                 fooddiary_count$food_name=="Radish" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*4.5,
                                 fooddiary_count$food_name=="Pumpkin" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*5000,
                                 fooddiary_count$food_name=="Green chili" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*45,
                                 fooddiary_count$food_name=="Potato" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*200,
                                 fooddiary_count$food_name=="Sweet potato" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*200,
                                 fooddiary_count$food_name=="Sheem" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100, # broad bean
                                 fooddiary_count$food_name=="Onion" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*150,
                                 fooddiary_count$food_name=="Tomato" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*40,
                                 fooddiary_count$food_name=="Sweet gourd" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*500,
                                 fooddiary_count$food_name=="Garlic" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*13,
                                 fooddiary_count$food_name=="Water gourd" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*145,
                                 fooddiary_count$food_name=="Drum stick" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100, # 26 cal / moringa
                                 fooddiary_count$food_name=="Carrot" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*70,
                                 fooddiary_count$food_name=="Green banana" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*30,
                                 fooddiary_count$food_name=="Cauliflower" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*550,
                                 fooddiary_count$food_name=="Danta (amaranth)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*45, # 170 cal
                                 fooddiary_count$food_name=="Green Papaya"~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*680,
                                 fooddiary_count$food_name=="Ash gourd" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*8000,
                                 fooddiary_count$food_name=="Cucumber" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*25,
                                 fooddiary_count$food_name=="Kachu (arum)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100, # 112 cal
                                 fooddiary_count$food_name=="Green mango" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*150,
                                 fooddiary_count$food_name=="Dhundal" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Kachur lati" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Green pea" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*18,
                                 fooddiary_count$food_name=="Green jackfruit" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*7937,
                                 fooddiary_count$food_name=="Mete alu" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*150,
                                 fooddiary_count$food_name=="Kakrol" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100, #spiny gourd
                                 fooddiary_count$food_name=="Soybean bori" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Beher gura" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100, # couldnt find
                                 fooddiary_count$food_name=="Shalgom" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*4.5, # turnip, couldnt find
                                 # fish large (avg large fish calorie count 1000)
                                 fooddiary_count$food_name=="Rui" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Telapia" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Swarputi" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Singi" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Grass Carp" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Taki" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Pangash" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Silver Carp" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Mrigel" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Kalibaus" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Hilsa" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Katla" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Jatka" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Aair" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Boal" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Dried fish" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 fooddiary_count$food_name=="Mirror Carp" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*1000,
                                 # spices (avg calorie count 5)
                                 fooddiary_count$food_name=="Dried chili" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*5,
                                 fooddiary_count$food_name=="Elachi" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*5,
                                 fooddiary_count$food_name=="Cinnamon" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*5,
                                 fooddiary_count$food_name=="Fresh Ginger" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*5,
                                 # other food (average serving size)
                                 fooddiary_count$food_name=="Pitha" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Ruti/Parota" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Singara" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Rice/Jao" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Piaju" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Cake" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Nimki" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Puri" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Alur chap" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Biscuit" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Bonroti/paoroti" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Khichuri" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Polao/Biryani/Tehari" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Chips" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Patties" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Chewing gum" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,                                               
                                 # vegetables (average serving size of 1 cup/128 grams)
                                 fooddiary_count$food_name=="Lal Shak (red amaranth)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Bathua" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Pat Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Dheki Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Pui (Indian spinach)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Dhania Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Lau Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Onion/garlic stalk" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Kalmi Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Radish leaves" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Kachu Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Kalo kachu Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Cabbage" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Helencha" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Katanate" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Palang Shak (spinach)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Pea leaves" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Drumstick leaves" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Mustard leaves" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Mixed leafy vegetables" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Dudhali Pata" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Khesari Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Swett gourd leaves" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Black gram leaves" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Geema Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Neem Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Darkuni Shak" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Bokful" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 fooddiary_count$food_name=="Litchis" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*128,
                                 # oil (serving size 15m)  
                                 fooddiary_count$food_name=="Soybean" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*15,
                                 fooddiary_count$food_name=="Mustard" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*15,
                                 fooddiary_count$food_name=="Dalda/banspati" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*15,
                                 fooddiary_count$food_name=="Red Palm Oil" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*15,
                                 fooddiary_count$food_name=="Ghee" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*15,
                                 fooddiary_count$food_name=="Sesame oil" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*15, 
                                 fooddiary_count$food_name=="Yellow Palm Oil" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*15,
                                 # fruit(avg serving size) 
                                 fooddiary_count$food_name=="Apple" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Mango" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Guava" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Banana" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Lemon" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Karambola" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Grapes" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Dates" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Jujube/dried jujube" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Coconut" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Orange" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Bel" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Tamarind" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Olive" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Chalta" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Pomelo" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Jack Fruit" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Pomelo" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Amra" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Papaya" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Black berry" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Green Coconut" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Dalim" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Tarmuj (Water melon)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Ata (bullock's heart)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Bangi (Musk melon)" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Pine apple" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Sobeda" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100,
                                 fooddiary_count$food_name=="Jaamrul" ~ fooddiary_count$calories_grams*fooddiary_count$food_type_quant*100)))))

# view data
# summary(fooddiary_count$calories_total_grams)

################################################
# FINAL FOOD DIARY DATAFRAME
# Each food item with calorie info including foods with food type unit = “count”.
# removed outliers
################################################
# merge fooddiary_count (unit = 8) and other dataset fooddiary_count to get complete df
fooddiary_nocounts <- fooddiary_cleaned %>% filter(food_type_unit != 8)
fooddiary_all <- rbind(fooddiary_nocounts, fooddiary_count)

# remove missing data 
fooddiary_all <- fooddiary_all[complete.cases(fooddiary_all),]

# remove outliers with custom outliers function (found at top of code)
fooddiary_all$calories_total_grams <- outliers(fooddiary_all$calories_total_grams)

# only use recall times of a week
fooddiary_all_week <- fooddiary_all %>% filter(recall=="week")

########################################################################################
# calculate proportions
########################################################################################
  
# meat
fooddiary_all_week <- fooddiary_all_week %>% mutate(isMeat = ifelse(food_name_type == "meategg",1,0))

    pct_meat <- fooddiary_all_week %>% group_by(hh_ID, week_number) %>% tally(isMeat)
    pct_meat <- pct_meat %>% mutate(numMeat = n) %>% select(-n)
    myfreqs <- fooddiary_all_week %>% group_by(hh_ID, week_number) %>% summarise(freq = n())
    pct_meat <- merge(myfreqs, pct_meat, by = c("hh_ID","week_number"))
    pct_meat <- pct_meat %>% mutate(pct_meat = numMeat/freq) %>% select(-numMeat, -freq)

# fish    
fooddiary_all_week <- fooddiary_all_week %>% mutate(isFish = ifelse(food_name_type == "fishlarge"|food_name_type == "fishsmall",1,0))
    
    pct_fish <- fooddiary_all_week %>% group_by(hh_ID, week_number) %>% tally(isFish)
    pct_fish <- pct_fish %>% mutate(numFish = n) %>% select(-n)
    myfreqs <- fooddiary_all_week %>% group_by(hh_ID, week_number) %>% summarise(freq = n())
    pct_fish <- merge(myfreqs, pct_fish, by = c("hh_ID","week_number"))
    pct_fish <- pct_fish %>% mutate(pct_fish = numFish/freq) %>% select(-numFish, -freq)
    

# protein
fooddiary_all_week <- fooddiary_all_week %>% mutate(isProtein = ifelse(food_name_type == "fishlarge"|
                                                                    food_name_type == "fishsmall"|
                                                                    food_name_type == "meategg",1,0))
    
    pct_protein <- fooddiary_all_week %>% group_by(hh_ID, week_number) %>% tally(isProtein)
    pct_protein <- pct_protein %>% mutate(numProtein = n) %>% select(-n)
    myfreqs <- fooddiary_all_week %>% group_by(hh_ID, week_number) %>% summarise(freq = n())
    pct_protein <- merge(myfreqs, pct_protein, by = c("hh_ID","week_number"))
    pct_protein <- pct_protein %>% mutate(pct_protein = numProtein/freq) %>% select(-numProtein, -freq)

####################################################################################################################################
## Find avg calories per person in each household
####################################################################################################################################

############################################
# find average calories by household
############################################
calories <- fooddiary_all_week %>% group_by(hh_ID, week_number) %>% tally(calories_total_grams)
calories <- calories %>% mutate(hh_calories_total = n) %>% select(-n)

df_calorie_avg <- merge(calories, hh_count, by = "hh_ID")

df_calorie_avg <- df_calorie_avg %>% mutate(avg_calories_member = hh_calories_total/hh_members) 

# create dataframe for graphs
df_food_basic1 <- df_calorie_avg %>% select(hh_ID, week_number, avg_calories_member)

# remove outliers with custom outliers function (found at top of code)
df_food_basic1$avg_calories_member <- outliers(df_food_basic1$avg_calories_member)

df <- merge(df_food_basic1, new_min, by = "week_number")

View(df)

# Merge with respondent and household data and food data

df_all <- merge(df, hh_respondent, by=c("hh_ID"))
df_all <- merge(df_all, pct_fish, by = c("hh_ID", "week_number"))
df_all <- merge(df_all, pct_meat, by = c("hh_ID", "week_number"))
df_all <- merge(df_all, pct_protein, by = c("hh_ID", "week_number"))
```

# Time Series
```{r fig.height = 3, fig.width = 3}
# (decomp_2 <- ggplot(df_all, aes(x = week_number, y = pct_meat)) +
# 	geom_point() +
# 	geom_smooth(method = "loess", se = FALSE, span = 0.6) +
# 	theme_classic() +geom_jitter())

# Extract month and year and store in separate columns
df_all$year <- format(df_all$week_date, format = "%Y")
df_all$month_num <- format(df_all$week_date, format = "%m")

# Create a colour palette using the `colortools` package 
library(colortools)
year_pal <- sequential(color = "darkturquoise", percentage = 100, what = "value")

# order factor 
df_all$week_number_f <- factor(df_all$week_number, levels = c(3:50), ordered=TRUE)

# # Make the plot
# (seasonal <- ggplot(df_all, aes(x = week_number_f, y = avg_calories_member, group = month_num)) +
# 	geom_line(aes(colour = month_num)) +
# 	theme_classic() + 
# 	scale_color_manual(values = year_pal))

# fishplot <- ggplot(df_all, aes(x=week_date, y=pct_fish)) #This will base plot which we'll manipulate.
# fishplot + geom_bar(stat="identity") + scale_x_date(breaks=date_breaks("1 week"))+ theme(axis.text.x = element_text(angle = 70))
# 
# meatplot <- ggplot(df_all, aes(x=week_date, y=pct_meat)) #This will base plot which we'll manipulate.
# meatplot + geom_bar(stat="identity") + scale_x_date(breaks=date_breaks("1 week"))+ theme(axis.text.x = element_text(angle = 70))

seasonal <- ggplot(df_all, aes(x = week_number, y = pct_meat)) +
	geom_point() +
	theme_classic() +
  scale_color_manual(values = year_pal) +
  geom_jitter()
seasonal

meatplot <- ggplot(df_all, aes(x=month_num, y=pct_meat, fill = year)) #This will base plot which we'll manipulate.
meatplot + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 70))

fishplot <- ggplot(df_all, aes(x=month_num, y=pct_fish, fill = year)) #This will base plot which we'll manipulate.
fishplot + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 70))

# Clustering

df <- hh_respondent
# remove NAs
df <- na.omit(df)
# check duplicates
df$hh_ID[duplicated(df$hh_ID)]
# remove duplicates
df <- df %>% distinct()
# remove inconsistencies
# 116180 had 70 reports, multple reports per week
# 110111 & 230347 reported more than once a week
df <- df %>% filter(hh_ID != 110111 & hh_ID != 230347 & hh_ID != 240476 & hh_ID != "116180"& hh_ID !=  "102020"& hh_ID !=  "107070"& hh_ID !=  "114153"& hh_ID !=  "115157"& hh_ID !=  "232379"& hh_ID !=  "232382"& hh_ID !=  "238450")  
# remove hh_ID for analysis
df_nohhID <- df %>% dplyr::select(-hh_ID)

# compute Gower distance
gower_dist <- daisy(df_nohhID, metric = "gower")
gower_mat <- as.matrix(gower_dist)

# print most similar households
# df_nohhID[which(gower_mat == min(gower_mat[gower_mat != min(gower_mat)]), arr.ind = TRUE)[1, ], ]
# options(max.print=1000000) # don't let rmd cut off results with max print default
# 
# print most dissimilar households
# df_nohhID[which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]), arr.ind = TRUE)[1, ], ]
# options(max.print=1000000) # don't let rmd cut off results with max print default

# identify number of clusters (2-8)
sil_width <- c(NA)
for(i in 2:8){  
  pam_fit <- pam(gower_dist, diss = TRUE, k = i)  
  sil_width[i] <- pam_fit$silinfo$avg.width  
}
plot(1:8, sil_width,
     xlab = "Number of clusters",
     ylab = "Silhouette Width")
lines(1:8, sil_width)

k <- 3 # number of clusters
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- df %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary

df[pam_fit$medoids,]

tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)

tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering),
         hh_ID = df$hh_ID)

ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster))

############################
# Clusters
############################
cluster1 <- tsne_data %>% filter(cluster == 1) 
cluster1 <- cluster1 %>% mutate(cluster = 1)
cluster1 <- cluster1 %>% dplyr::select(hh_ID, cluster)

cluster2 <- tsne_data %>% filter(cluster == 2) 
cluster2 <- cluster2 %>% mutate(cluster = 2)
cluster2 <- cluster2 %>% dplyr::select(hh_ID, cluster)

cluster3 <- tsne_data %>% filter(cluster == 3)
cluster3 <- cluster3 %>% mutate(cluster = 3)
# cluster3 <- cluster3 %>% dplyr::select(hh_ID, cluster3)
cluster3 <- data.frame(cluster3$hh_ID, cluster3$hh_ID)
cluster3 <- cluster3 %>% dplyr::mutate(hh_ID=cluster3.hh_ID, cluster=3)
cluster3 <- cluster3 %>% dplyr::select(hh_ID,cluster)

clusters <- rbind(cluster1, cluster2, cluster3)
tsne_data <- merge(tsne_data, clusters, by = c("hh_ID"))

## Compare Clusters Visually
temp <- merge(tsne_data, df_all, by = c("hh_ID"))
temp$cluster <- factor(temp$cluster)

(seasonal <- ggplot(temp, aes(x = week_number_f, y = avg_calories_member, group = cluster)) +
	geom_line(aes(colour = cluster)) +
	theme_classic() +
	scale_color_manual(values = year_pal))

write.csv(temp, "final_data.csv")
```

